Activate active storage
diliaaragon/marketplace pull request #13
Opened 2019-04-12 20:40 UTC by diliaaragon

2019-05-02 21:21 UTC, juankhazbun requested changes

2019-05-02 21:21 UTC, juankhazbun commented on .byebug_history
> +exit
Agrega este archivo al .gitignore

2019-05-02 21:56 UTC, diliaaragon commented on .byebug_history
> +exit
Listo

2019-05-03 15:59 UTC, juankhazbun approved these changes
👍

2019-05-03 16:00 UTC, merged