Categories model
diliaaragon/marketplace pull request #16
Opened 2019-04-15 21:34 UTC by diliaaragon

- Create the model categories and execute the migrations.

- Add the validations to the model.

2019-05-02 21:26 UTC, juankhazbun requested changes

2019-05-02 21:26 UTC, juankhazbun commented on app/models/category.rb
> +  validates :name, presence: true
Agregar uniqueness para que el nombre no se repita

2019-05-02 21:26 UTC, juankhazbun commented on db/schema.rb
> +  create_table "active_storage_attachments", force: :cascade do |t|
Esto no debería estar en este PR.

2019-05-02 21:26 UTC, juankhazbun commented on db/schema.rb
> +  create_table "active_storage_blobs", force: :cascade do |t|
Esto no debería estar en este PR.

2019-05-02 22:12 UTC, diliaaragon commented on app/models/category.rb
> +  validates :name, presence: true
Listo

2019-05-03 16:07 UTC, juankhazbun approved these changes

2019-05-03 16:07 UTC, merged