Add administrator
diliaaragon/marketplace pull request #18
Opened 2019-04-16 16:55 UTC by diliaaragon

Add the gem Rails admin in my gemfile, install them and execute the migrations

2019-05-02 21:29 UTC, juankhazbun requested changes

2019-05-02 21:29 UTC, juankhazbun commented on Gemfile
> +gem 'rails_admin_rollincode', '~> 1.0'
¿Para que se utiliza esta gema?

2019-05-02 22:15 UTC, diliaaragon commented on Gemfile
> +gem 'rails_admin_rollincode', '~> 1.0'
esta gem 'rails_admin_rollincode', '~> 1.0'?
Para el tema de la pagina del admin y la otra es para usar el rails admin

2019-05-06 20:21 UTC, juankhazbun approved these changes
👍

2019-05-06 20:21 UTC, merged