Add status to products
diliaaragon/marketplace pull request #21
Opened 2019-04-23 16:23 UTC by diliaaragon

- Add a state machine to the model products using the gem 'AASM'

2019-05-02 21:32 UTC, juankhazbun requested changes

2019-05-02 21:32 UTC, juankhazbun commented on Gemfile
> +gem 'aasm'
Agregar la versión.

2019-05-02 21:32 UTC, juankhazbun commented on app/models/product.rb
> +    event :file do
Cambiar nombre de **file** a **archive**

2019-05-03 15:56 UTC, diliaaragon commented on Gemfile
> +gem 'aasm'
listo

2019-05-03 15:56 UTC, diliaaragon commented on app/models/product.rb
> +    event :file do
listo

2019-05-06 23:17 UTC, juankhazbun requested changes

2019-05-06 23:17 UTC, juankhazbun commented on Gemfile
> +gem 'aasm'
Agregar la versión.

2019-05-08 19:50 UTC, juankhazbun requested changes

2019-05-08 19:50 UTC, juankhazbun commented on app/models/product.rb
> +  include AASM
Mueve esta linea al comienzo. Linea 5.

2019-05-08 19:56 UTC, diliaaragon commented on app/models/product.rb
> +  include AASM
listo

2019-05-08 20:12 UTC, juankhazbun requested changes

2019-05-08 20:12 UTC, juankhazbun commented on app/controllers/products_controller.rb
> +    @product = Product.find(params[:id])
Estas repitiendo esta linea en multiples partes... vuelvela un metodo o un before_action

2019-05-08 20:24 UTC, diliaaragon commented on app/controllers/products_controller.rb
> +    @product = Product.find(params[:id])
listo

2019-05-13 20:46 UTC, juankhazbun approved these changes

2019-05-13 20:46 UTC, merged