Add mailer
diliaaragon/marketplace pull request #35
Opened 2019-05-13 16:36 UTC by diliaaragon

- Add mailer to send emails when a product is published
**Refences**
#21 Add status to product

2019-05-28 22:10 UTC, juankhazbun requested changes

2019-05-28 22:10 UTC, juankhazbun commented on app/mailers/application_mailer.rb
> +  default from: 'dilia.aragon@koombea.com'
Aquí deberias usar un from como **no-reply@shoppy.com**

2019-05-28 22:11 UTC, juankhazbun requested changes

2019-05-28 22:11 UTC, juankhazbun commented on config/initializers/smtp_settings.rb
> +ActionMailer::Base.smtp_settings = {
este initializer si lo necesitas? veo las variables quemadas en el env de production arriba

2019-05-28 22:20 UTC, diliaaragon commented on app/mailers/application_mailer.rb
> +  default from: 'dilia.aragon@koombea.com'
listo

2019-05-28 22:20 UTC, diliaaragon commented on config/initializers/smtp_settings.rb
> +ActionMailer::Base.smtp_settings = {
listo

2019-05-31 19:59 UTC, juankhazbun requested changes

2019-05-31 19:59 UTC, juankhazbun commented on config/environments/production.rb
> +  config.action_mailer.default_url_options = { host: "https://warm-journey-20883.herokuapp.com/" }
esto deberia ser una variable de entorno

2019-06-04 21:09 UTC, diliaaragon commented on config/environments/production.rb
> +  config.action_mailer.default_url_options = { host: "https://warm-journey-20883.herokuapp.com/" }
listo

2019-06-07 19:24 UTC, juankhazbun approved these changes

2019-06-07 19:24 UTC, merged