Add Rspec and gems for test
diliaaragon/marketplace pull request #44
Opened 2019-05-30 15:34 UTC by diliaaragon

2019-06-07 19:26 UTC, juankhazbun requested changes

2019-06-07 19:26 UTC, juankhazbun commented on config/application.rb
> +    config.factory_bot.definition_file_paths = ["custom/factories"]
No tenias que quitar esa linea?

2019-06-07 19:26 UTC, juankhazbun commented on spec/factories/user.rb
> +    first_name { "John" }
Utiliza Faker

2019-06-07 19:27 UTC, juankhazbun requested changes

2019-06-07 19:27 UTC, juankhazbun commented on spec/factories/product.rb
> +    description  { "un producto" }
Utiliza Faker

2019-06-07 20:49 UTC, diliaaragon commented on config/application.rb
> +    config.factory_bot.definition_file_paths = ["custom/factories"]
listo

2019-06-07 20:49 UTC, diliaaragon commented on spec/factories/product.rb
> +    description  { "un producto" }
listo

2019-06-07 21:29 UTC, diliaaragon commented on spec/factories/user.rb
> +    first_name { "John" }
listo

2019-06-11 15:24 UTC, juankhazbun approved these changes

2019-06-11 15:24 UTC, merged